<?php

namespace LeapQueue;

use PDO;
use LeapQueue\Interfaces\CanMigrateInterface;
use LeapQueue\Traits\DatabaseTrait;
use LeapQueue\Traits\FactoryTrait;
use LeapQueue\Traits\OrmTrait;

class Queue implements CanMigrateInterface
{    
    use DatabaseTrait, FactoryTrait, OrmTrait;

    protected static $tableName = 'queues';

    /**
     * Fields that can be updated or inserted (not generated by database)
     * @var array
     */
    protected $mutableFields = ['code'];    

    /**     
     * See documentation of the setConnection method in the DatabaseTrait.
     * 
     * @param array $config
     * @param PDO $db     
     * @return void
     */
    public static function boot( array $config, ?PDO $db = null ) : void
    {
        $dbConfig = $config['database'] ?? [];

        static::setConnection($dbConfig, $db);
        QueueGroup::setConnection($dbConfig, static::$db);
        Job::setConnection($dbConfig, static::$db);
    }

    public static function migrateAll()
    {
        return self::migrateOrDownAll('migrate');
    }  

    public static function downAll()
    {
        return self::migrateOrDownAll('down');
    }
    
    protected static function migrateOrDownAll( string $method ) : bool
    {
        if( !in_array($method, ['migrate', 'down']) ) {
            throw new \InvalidArgumentException('Method must be either migrate or down');
        }

        $migrationClasses = [
            self::class,
            QueueGroup::class,
            Job::class
        ];

        // Count number of successful actions against the database
        $successes = 0;

        foreach( $migrationClasses as $class ) {
            
            $interfaces = class_implements($class);

            if( in_array(CanMigrateInterface::class, $interfaces) ) {
                $successes += $method === 'down' ? $class::down() : $class::migrate();
            }

        }
        
        return count($migrationClasses) === $successes;
    }

    public static function migrate() : bool
    {
        $sql = "
            CREATE TABLE IF NOT EXISTS ". static::getTableName() ." (    
                -- Column Definitions
                id SMALLINT UNSIGNED AUTO_INCREMENT,
                code VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),    
                
                -- Indexes
                PRIMARY KEY (id),
                UNIQUE INDEX idx_unique_code (code)
            ) ENGINE=InnoDb COMMENT='Table created and managed by LeapQueue'
        ";
        return static::$db->exec($sql);
    }

    public static function down() : bool
    {        
        static::$db->exec("SET FOREIGN_KEY_CHECKS = 0");        
        $result = static::$db->exec("DROP TABLE IF EXISTS " . static::getTableName());
        static::$db->exec("SET FOREIGN_KEY_CHECKS = 1");

        return $result;
    }

}
